# Generated by Django 3.1.7 on 2021-03-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=120, null=True)),
                ('product_name', models.CharField(max_length=120, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('stock', models.DecimalField(decimal_places=0, max_digits=100)),
                ('desc', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, default='farmers/product_default.png', null=True, upload_to=''),
        ),
    ]
