# Generated by Django 3.1.7 on 2021-04-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_auto_20210403_1312'),
    ]

