# Generated by Django 3.1.4 on 2021-04-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_auto_20210403_1530'),
        ('farmers', '0003_auto_20210403_1505'),
    ]

    operations = [
    ]
