# Generated by Django 3.1.4 on 2021-04-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0006_merge_20210403_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='min_purchase',
        ),
    ]
