# Generated by Django 3.1.4 on 2021-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0008_goods_min_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='min_purchase',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=100),
        ),
    ]
