# Generated by Django 3.1.4 on 2021-04-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0009_goods_min_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, default='product_default.png', null=True, upload_to=''),
        ),
    ]
