# Generated by Django 3.1.4 on 2021-04-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0012_auto_20210403_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='customercart',
            name='total_cost',
        ),
    ]
