# Generated by Django 3.1.4 on 2021-04-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0013_auto_20210404_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercart',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.customer'),
        ),
    ]
