# Generated by Django 3.1.4 on 2021-04-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0014_auto_20210404_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.customer'),
        ),
    ]
