# Generated by Django 3.1.4 on 2021-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0015_goods_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, default='rice.jpg', null=True, upload_to=''),
        ),
    ]
