# Generated by Django 3.1.7 on 2021-05-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0018_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
