# Generated by Django 3.1.7 on 2021-05-30 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0019_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodsComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.goods')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.goodscomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
