# Generated by Django 3.1.4 on 2021-06-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0019_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
