# Generated by Django 3.1.4 on 2021-06-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0020_auto_20210601_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
