# Generated by Django 3.1.7 on 2021-05-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0020_goodscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscomment',
            name='parent',
        ),
    ]
