# Generated by Django 3.1.7 on 2021-06-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0021_auto_20210601_1103'),
        ('farmers', '0022_auto_20210530_1946'),
    ]

    operations = [
    ]
