# Generated by Django 3.1.7 on 2021-06-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0023_merge_20210601_1343'),
        ('farmers', '0023_merge_20210601_1153'),
    ]

    operations = [
    ]
