# Generated by Django 3.1.7 on 2021-06-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0024_merge_20210602_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='min_purchase',
        ),
        migrations.AddField(
            model_name='equipments',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.customer'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='image',
            field=models.ImageField(blank=True, default='product_default.jpg', null=True, upload_to=''),
        ),
    ]
