# Generated by Django 3.1.7 on 2021-06-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0025_auto_20210602_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='image',
            field=models.ImageField(blank=True, default='product_default.png', null=True, upload_to=''),
        ),
    ]
