# Generated by Django 3.1.7 on 2021-06-03 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0027_auto_20210602_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.equipments'),
        ),
    ]
